### PR TITLE
Capstone Project

### PR DESCRIPTION
**Pull request by shegy28**
### I was able to complete this project by doing the following:

**Added an index.html file**

- Made  Flexboxes to arrange the page.
- Created navigations to different parts of the project.
- Created mobile navigation with a hamburger icon that displays the elements in it.

**Added a styles.css file**

- Created different styling for different screen sizes: Mobile (<768px) and Desktop (>768px).
- Styled the mobile navigation and all elements in it.

**Added a script.js file**

- Made use of Loops and innerHTML to load HTML content to the page.
- Made use of Objects and Arrays to store and retrieve information for the page.
- Made use of query selectors to point to elements in the HTML page. Added a .gitignore file

Ignored node_modules
Made use of Linters to check for errors in the JavaScript, CSS, and HTML files.
Update the README file to give a clear explanation of the project. This file includes the following
Loom Video Recording: A video of me explaining the project. [Click Here](https://www.loom.com/share/c133879ea96a4e29846be2e0390ac07f).
Link to live Demo.  [Click Here](https://shegy28.github.io/Fashion-week/index.html).

### CODE REVIEW

**Review by Qoosim — CHANGES_REQUESTED** [review]
#  *Status: Required Changes* :recycle:

Hi @shegy28, 

Good job so far!
There are some issues that you still need to work on to prepare your project for the final evaluation but you are almost there!

## Top Highlights
-  No linter errors. :heavy_check_mark: 
-  Correct GitHub Flow. :heavy_check_mark: 
-  Descriptive PR title and summary. :heavy_check_mark: 
-  Good Presentation Video. :heavy_check_mark: 



## Suggested changes
_Check the comments under the review._

You can use as many of my suggestions as you want. If there is anything you would like to skip - feel free to do that. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

- [ ] For your about page, there's an extra section that's supposed to not be there. Kindly compare the content of your about page and that of guiding template and remove the extra for the desktop version. Please, take a look

### Your Design: About page for Desktop version
your-about-extral

### Guiding Template: About page for Desktop version
temp-about-no-extral

- [x] Kindly look at the footer background colour for about page for desktop version and change the bg color of your design to that. Presently the bg color for your about footer for desktop version is white and that's different to what's on the guiding template. Kindly give it a closer look and modify your design along that direction. Please take a look.

### Your Design: About page footer for desktop version
your-about-footer-bg

### Guiding template: About page footer for desktop version
temp-footer

- [ ] Kindly take a look at the new [Readme template](https://github.com/microverseinc/readme-template) from Microverse and use that to make your professional README file.

**Comment by shegy28** [comment]
@Qoosim Good day i hope you are okay. I got your feedback and i have questions. 

- As per the Footer section of the about us page and the added section, it was done on purpose so the website feel more vibrant and the instructions told us to design with more freedom so i think you should check with other reviewers to be sure you are not making me do a change to design that is not required.
- Also i made my footer like that too as we are not supposed to follow the designer in total but we have to be creative with it. So please check with other reviewers and get back to me. Because i have colleges who have similar about us page with me and the added section too and the projects have been approved.
-

**Comment by shegy28** [comment]
@Qoosim Also using the new readme file is not part of the requirement. I did not use it because i do not really understand it yet. So please check again and let me know if this changes are really important

**Comment by Qoosim** [comment]
> @Qoosim Good day i hope you are okay. I got your feedback and i have questions.
> 
> * As per the Footer section of the about us page and the added section, it was done on purpose so the website feel more vibrant and the instructions told us to design with more freedom so i think you should check with other reviewers to be sure you are not making me do a change to design that is not required.
> * Also i made my footer like that too as we are not supposed to follow the designer in total but we have to be creative with it. So please check with other reviewers and get back to me. Because i have colleges who have similar about us page with me and the added section too and the projects have been approved.

@shegy28, thanks for making your idea known. The fact that some reviewers overlooked that part does not mean it is right. You're required to follow the guiding template as close as possible but with freedom to change the content. Your must not provide four columns in a section where there're five or six columns on the guiding design. The instructions we follow while reviewing your code is to ensure that you learn how to follow clients demand as close as possible. You do not need to present what you think is right for your client but to follow your client demand. We have rules that we follow while reviewing students PR. We do have list of content we check for in your code. We might forget to check it all sometime, which is normal to every human being. If some areas are overlooked by some reviewers, is not sufficed to say every other reviewers must overlook them. Please, we give suggestions to make your code better, not to put you into unnecessary stress.

**Review by Nemwel-Boniface — APPROVED** [review]
## Hello @shegy28       :wave: ,
I am Nemwel your reviewer for this PR :man_beard:  

Thank you for meeting all the project requirements good job! :partying_face: 
Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! :partying_face: 🎉 



## Highlights

Great job setting up the correct linters ✔️ 
Professional documentation ✔️ 
Correct workflow ✔️ 
Meaningful commit messages ✔️ 
Met all the milestone requirements ✔️ 

## [Optional] suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me **@Nemwel-Boniface** in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
